[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "thethinker-mcp"
version = "0.1.0"
description = "MCP server for your repository"
dependencies = [
    "mcp>=1.0.0"
]

[project.scripts]
thethinker-mcp = "src.server:main"
